apiVersion: batch/v1
kind: Job
metadata:
  name: job01
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: job
        image: redhat/ubi9
        command: ["sleep",  "30"]
