apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
data:
  username: cmFnaHU=
  password: YWJjZEAxMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo1
spec:
  containers:
    - name: demo
      image: rkalluru/learnk8s:rhel9-bare
      env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: username
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo2
spec:
  containers:
    - name: demo
      image: rkalluru/learnk8s:rhel9-bare
      envFrom:
        - secretRef:
            name: secret-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo3
spec:
  containers:
    - name: demo
      image: rkalluru/learnk8s:rhel9-bare
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: config
    secret:
      secretName: secret-demo

