apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  labels:
    topic: services
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-cip
spec:
  selector:
    topic: services
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: 80 # Container Port
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: redhat
    image: rkalluru/learnk8s:rhel9-bare




